
[project]
name = "friedger-smart-contracts"
description = ""
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = [
    { contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait" },
    { contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard" },
]

[contracts.history]
path = "contracts/experiments/history.clar"

[contracts.flip-coin]
path = "contracts/experiments/flip-coin.clar"
depends_on = []

[contracts.flip-coin-tax-office]
path = "contracts/experiments/flip-coin-tax-office.clar"

[contracts.flip-coin-delegate]
path = "contracts/experiments/flip-coin-delegate.clar"

[contracts.flip-coin-jackpot]
path = "contracts/experiments/flip-coin-jackpot.clar"

[contracts.flip-coin-at-two]
path = "contracts/experiments/flip-coin-at-two.clar"

[contracts.perishable-token]
path = "contracts/tokens/perishable-token.clar"

[contracts.panic]
path = "contracts/experiments/panic.clar"

[contracts.beeple]
path = "contracts/tokens/beeple.clar"

[contracts.fungible-token]
path = "contracts/tokens/fungible-token.clar"

[contracts.trait-conversion]
path = "contracts/experiments/trait-conversion.clar"
clarity_version = 2
epoch = "2.1"

[contracts.trait-conversion-router]
path = "contracts/experiments/trait-conversion-router.clar"
clarity_version = 2
epoch = "2.1"


## Test contracts
[contracts.perishable-token_test]
path = "test/perishable-token_test.clar"
clarity_version = 2
epoch = "2.1"

[contracts.trait-conversion-router_test]
path = "test/trait-conversion-router_test.clar"
clarity_version = 2
epoch = "2.1"


## REPL
[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }

# Check-checker settings:
# trusted_sender: if true, inputs are trusted after tx_sender has been checked.
# trusted_caller: if true, inputs are trusted after contract-caller has been checked.
# callee_filter: if true, untrusted data may be passed into a private function without a
# warning, if it gets checked inside. This check will also propagate up to the
# caller.
# More informations: https://www.hiro.so/blog/new-safety-checks-in-clarinet
